- hosts: all
  become: yes
  tasks:

    - name: Install supporting software
      yum:
        name:
          - java-1.8.0-openjdk

    - name: Create dropwiz user
      user:
        name: dropwiz
        system: yes

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/dans.knaw.nl/bin/
        - /etc/opt/dans.knaw.nl/dropwiz-simple/

    - name: Copy jar
      copy:
        src: target/dropwiz-simple-scala-1.0-SNAPSHOT.jar
        dest: /opt/dans.knaw.nl/bin/

    - name: Copy config
      copy:
        src: example.yml
        dest: /etc/opt/dans.knaw.nl/dropwiz-simple/app.yml

    - name: Copy systemd unit
      copy:
        src: dropwiz-simple.service
        dest: /usr/lib/systemd/system/

